"""T2 sensitivity checks for context leakage in intervention candidates."""

from __future__ import annotations

import json
from math import sqrt
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from ..runtime.canonical import canonical_hash
from ..runtime.paths import resource_path
from .causal import CausalCase
from .common import TrackReceipt, make_track_receipt


class CausalSensitivityEvaluation(BaseModel):
    """Metrics for a bounded negative-control sensitivity experiment."""

    model_config = ConfigDict(extra="forbid")

    evaluator_id: str = "causal-context-sensitivity-v1"
    baseline_train_rmse: float = Field(ge=0)
    baseline_holdout_rmse: float = Field(ge=0)
    context_leak_train_rmse: float = Field(ge=0)
    context_leak_holdout_rmse: float = Field(ge=0)
    context_leakage_coefficient: float
    context_leakage_rejected: bool
    passed: bool
    notes: list[str]


def _rmse(
    cases: list[CausalCase],
    *,
    coefficient: float,
    intercept: float,
    context_coefficient: float,
) -> float:
    if not cases:
        raise ValueError("causal sensitivity split cannot be empty")
    residuals = [
        coefficient * item.intervention_value
        + context_coefficient * item.context_value
        + intercept
        - item.expected_outcome
        for item in cases
    ]
    return sqrt(sum(value * value for value in residuals) / len(residuals))


def evaluate_context_sensitivity(
    cases: list[CausalCase],
    *,
    coefficient: float = 2.0,
    intercept: float = 1.0,
    context_leakage_coefficient: float = 0.25,
    max_rmse: float = 1e-12,
) -> tuple[CausalSensitivityEvaluation, TrackReceipt]:
    """Reject a candidate that uses context in a do(intervention) outcome.

    The fixture declares outcomes generated by the intervention value only.  The
    negative candidate adds a fixed context term, so its holdout error is tested
    independently from the baseline candidate.  This is a synthetic semantic
    control; it is not a claim about exchangeability or real interventions.
    """

    train = [item for item in cases if item.split == "train"]
    holdout = [item for item in cases if item.split == "holdout"]
    if not train or not holdout:
        raise ValueError("causal sensitivity fixture requires train and holdout cases")
    baseline_train = _rmse(
        train, coefficient=coefficient, intercept=intercept, context_coefficient=0.0
    )
    baseline_holdout = _rmse(
        holdout, coefficient=coefficient, intercept=intercept, context_coefficient=0.0
    )
    leak_train = _rmse(
        train,
        coefficient=coefficient,
        intercept=intercept,
        context_coefficient=context_leakage_coefficient,
    )
    leak_holdout = _rmse(
        holdout,
        coefficient=coefficient,
        intercept=intercept,
        context_coefficient=context_leakage_coefficient,
    )
    leakage_rejected = leak_holdout > max_rmse
    passed = baseline_holdout <= max_rmse and leakage_rejected
    evaluation = CausalSensitivityEvaluation(
        baseline_train_rmse=baseline_train,
        baseline_holdout_rmse=baseline_holdout,
        context_leak_train_rmse=leak_train,
        context_leak_holdout_rmse=leak_holdout,
        context_leakage_coefficient=context_leakage_coefficient,
        context_leakage_rejected=leakage_rejected,
        passed=passed,
        notes=[
            "Baseline outcome is declared to depend on do(intervention_value) only.",
            "The negative candidate adds context_value and must fail the holdout gate.",
            "Synthetic context-leakage rejection does not establish real causal identification.",
        ],
    )
    receipt = make_track_receipt(
        track_id="T2",
        evaluator_id=evaluation.evaluator_id,
        input_payload={
            "cases": [item.model_dump(mode="json") for item in cases],
            "coefficient": coefficient,
            "intercept": intercept,
            "context_leakage_coefficient": context_leakage_coefficient,
            "max_rmse": max_rmse,
        },
        evidence_level="validated-reproduction" if passed else "demo",
        passed=passed,
        negative_case_passed=leakage_rejected,
        result=evaluation.model_dump(mode="json"),
        blocked_gates=[
            "real-world intervention data",
            "causal identification",
            "source and measurement rights",
        ],
    )
    return evaluation, receipt


def load_builtin_cases() -> list[CausalCase]:
    """Load the byte-stable causal fixture from checkout or an installed wheel."""

    payload: dict[str, Any] = json.loads(
        resource_path("examples/causal/fixture.json").read_text(encoding="utf-8")
    )
    if payload.get("schema_version") != "causal-fixture-v1":
        raise ValueError("unsupported causal fixture")
    return [CausalCase.model_validate(item) for item in payload["cases"]]


def candidate_set_hash() -> str:
    return canonical_hash(["causal-intervention-v1", "causal-context-leak-v1"])
